#!/bin/bash

IMAGE="asteroids:0.1.0"
NAME="dasteroids"

build() {
	docker build . -t $IMAGE
}

container() {
	if [[ -n $(docker ps -a | grep $NAME) ]]; then
		clean
	fi

	xhost local:root
	docker run -it \
		-v /tmp/.X11-unix:/tmp/.X11-unix \
		-e "DISPLAY=unix${DISPLAY}" \
		--device /dev/dri \
		--name $NAME \
		$IMAGE
	xhost -local:root
}

clean() {
	docker stop $NAME
	docker rm $NAME
}

$*
